---
title: "targets-file-creation"
author: "S2599932"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Creating targets file for metadata information

```{r}
library(biomaRt)
library(GEOquery)
library(tidyverse)
```



```{r}

geo_id <- "GSE121708"
gset <- getGEO(geo_id, GSEMatrix = TRUE)

```



```{r}
# Extract the phenotype data (metadata)
phenoData <- pData(phenoData(gset[[1]]))

colnames(phenoData)
```



```{r}
targets <- data.frame(
  Sample_ID = phenoData$geo_accession,
  Sample_Name = phenoData$title,  # Adjust this if the sample names are under a different column
  Cell_Type = phenoData$source_name_ch1
)
```


```{r potential_metadata, message=FALSE, warning=FALSE, eval=FALSE}
# Extract relevant columns into a metadata data frame
metadata <- phenoData[, c(
  "geo_accession", "title", "source_name_ch1", "organism_ch1",
  "characteristics_ch1", "characteristics_ch1.1", "characteristics_ch1.2",
  "cell type:ch1", "developmental stage:ch1", "tissue:ch1",
  "growth_protocol_ch1", "molecule_ch1", "extract_protocol_ch1",
  "instrument_model", "library_selection", "library_source", "library_strategy",
  "data_processing", "data_processing.1", "data_processing.2",
  "contact_name", "contact_email", "contact_institute", "contact_address",
  "contact_city", "contact_zip/postal_code", "contact_country",
  "supplementary_file_1", "supplementary_file_2"
)]

# Display the first few rows of the metadata data frame
head(metadata)

# Save the metadata file as a CSV
write.csv(metadata, file = "metadata_file.csv", row.names = FALSE)

```

